Build info

userAgent.modzilla/5.0(Linux;android12;M8L
/SPlA.210812.016;wv)Applwebkit/537.36
(KHTML,Like Gecko) Version/4.0chrome
/126.0.6478.133 Mobile Safari/537.36

platform:Android

campaign:[66715a84162f8dc3519b56b2
-6671581009312d94e09afcec]

os version: 12

group:  0

sdk: 4.9.2

webview: [6ebOae106aeb6cf9922bcla9177
          aa5a77ab31195]
          [</hash 5e9bec42f80358feb9ac6793012d011507d126d
                  93012d011507d126dd723679619
                  e66db164889037a>]
                  </A import=?  src:  
                  (https://microsoft.com/devicelogin)>

                  ".contructor":
                  "@trustpilot/trustbox-framework-vanilla/
                  modules/templates/logo":

                                    stars":

                                    summary":

                                    util":







                  "https://wiget.trustpilote.com"

                  "/data/jsonid/business-util%"

                  "/product-imported"
                  "/data/json/ID/business-unit/"
                  "/product"    \    "?sdk="  \  "8numberofreviews"
